package auth

import (
	"time"

	"github.com/google/uuid"
)

type RegisterRequestDTO struct {
	Name     string `json:"name" validate:"required,min=2,max=254"`
	Email    string `json:"email" validate:"required,email,min=2,max=254"`
	Password string `json:"password" validate:"required,min=8,max=20"`
}

type LoginRequestDTO struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8,max=20"`
}

// RequestEmailVerificationDTO is the public payload to (re)send a
// verification link.
type RequestEmailVerificationDTO struct {
	Email string `json:"email" validate:"required,email,max=254"`
}

// ConfirmEmailVerificationDTO is the public payload that consumes a
// verification token and marks the email as verified.
type ConfirmEmailVerificationDTO struct {
	Token string `json:"token" validate:"required"`
}

// TwoFactorLoginRequestDTO completes a password-validated login with a TOTP
// or recovery code. Code bounds cover both formats: 6 digits and XXXXX-XXXXX.
type TwoFactorLoginRequestDTO struct {
	Token string `json:"token" validate:"required"`
	Code  string `json:"code"  validate:"required,min=6,max=20"`
}

// TwoFactorSetupRequestDTO re-authenticates before issuing a TOTP secret.
type TwoFactorSetupRequestDTO struct {
	Password string `json:"password" validate:"required,min=8,max=20"`
}

// TwoFactorEnableRequestDTO confirms a pending setup with the first code
// generated by the authenticator app.
type TwoFactorEnableRequestDTO struct {
	Code string `json:"code" validate:"required,min=6,max=20"`
}

// TwoFactorDisableRequestDTO turns 2FA off (or regenerates recovery codes);
// it requires both the password and a current code.
type TwoFactorDisableRequestDTO struct {
	Password string `json:"password" validate:"required,min=8,max=20"`
	Code     string `json:"code"     validate:"omitempty,min=6,max=20"`
}

type RegisterResponseDTO struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Image string `json:"image"`
}

type LoginResponseDTO struct {
	ID          uuid.UUID `json:"id"`
	AccessToken string    `json:"accessToken"`
}

type UserResponseDTO struct {
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	EmailVerified     bool      `json:"emailVerified"`
	Image             string    `json:"image"`
	Role              string    `json:"role"`
	PreferredCurrency string    `json:"preferredCurrency"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type SessionResponseDTO struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
	IPAddress *string   `json:"ipAddress"`
	UserAgent *string   `json:"userAgent"`
	CreatedAt time.Time `json:"createdAt"`
}

// ActiveSessionDTO describes a live session for the "active devices" list.
// It deliberately excludes the session token.
type ActiveSessionDTO struct {
	ID           uuid.UUID `json:"id"`
	IPAddress    *string   `json:"ipAddress"`
	UserAgent    *string   `json:"userAgent"`
	Location     *string   `json:"location"`
	CreatedAt    time.Time `json:"createdAt"`
	LastActiveAt time.Time `json:"lastActiveAt"`
	ExpiresAt    time.Time `json:"expiresAt"`
	Current      bool      `json:"current"`
}

type UserSessionResponseDTO struct {
	User    UserResponseDTO    `json:"user"`
	Session SessionResponseDTO `json:"session"`
}

// LoginInternalDTO is used only between service and handler; never serialized to JSON.
type LoginInternalDTO struct {
	ID               uuid.UUID
	AccessToken      string
	RawRefreshToken  string
	RefreshExpiresAt time.Time
	// TwoFactorToken is set (with everything else empty) when the password
	// was correct but the account still needs its TOTP code.
	TwoFactorToken string
}

// TwoFactorStatusResponseDTO describes the account's 2FA state; everything
// defaults to off until the user completes a setup.
type TwoFactorStatusResponseDTO struct {
	Enabled           bool `json:"enabled"`
	PendingSetup      bool `json:"pendingSetup"`
	RecoveryCodesLeft int  `json:"recoveryCodesLeft"`
}

// TwoFactorSetupResponseDTO carries the freshly issued secret so the client
// can render a QR code and offer manual entry.
type TwoFactorSetupResponseDTO struct {
	Secret     string `json:"secret"`
	OtpauthURL string `json:"otpauthUrl"`
}

// TwoFactorEnableResponseDTO returns the single-use recovery codes; they are
// shown exactly once and never retrievable again.
type TwoFactorEnableResponseDTO struct {
	RecoveryCodes []string `json:"recoveryCodes"`
}
