package auth

type RegisterRequestDTO struct {
	Name     string `json:"name" validate:"required,min=2,max=254"`
	Email    string `json:"email" validate:"required,email,min=2,max=254"`
	Password string `json:"password" validate:"required,min=8,max=20"`
}

type LoginRequestDTO struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8,max=20"`
}

// RequestPasswordResetDTO is the public payload to ask for a reset link.
type RequestPasswordResetDTO struct {
	Email string `json:"email" validate:"required,email,max=254"`
}

// ConfirmPasswordResetDTO is the public payload that consumes a reset token
// and sets a new password. Password bounds mirror LoginRequestDTO so login
// never rejects a password set here.
type ConfirmPasswordResetDTO struct {
	Token    string `json:"token"    validate:"required"`
	Password string `json:"password" validate:"required,min=8,max=20"`
}

// RequestEmailVerificationDTO is the public payload to (re)send a
// verification link.
type RequestEmailVerificationDTO struct {
	Email string `json:"email" validate:"required,email,max=254"`
}

// ConfirmEmailVerificationDTO is the public payload that consumes a
// verification token and marks the email as verified.
type ConfirmEmailVerificationDTO struct {
	Token string `json:"token" validate:"required"`
}

// TwoFactorLoginRequestDTO completes a password-validated login with a TOTP
// or recovery code. Code bounds cover both formats: 6 digits and XXXXX-XXXXX.
type TwoFactorLoginRequestDTO struct {
	Token string `json:"token" validate:"required"`
	Code  string `json:"code"  validate:"required,min=6,max=20"`
}

// TwoFactorSetupRequestDTO re-authenticates before issuing a TOTP secret.
type TwoFactorSetupRequestDTO struct {
	Password string `json:"password" validate:"required,min=8,max=20"`
}

// TwoFactorEnableRequestDTO confirms a pending setup with the first code
// generated by the authenticator app.
type TwoFactorEnableRequestDTO struct {
	Code string `json:"code" validate:"required,min=6,max=20"`
}

// TwoFactorDisableRequestDTO turns 2FA off (or regenerates recovery codes);
// it requires both the password and a current code.
type TwoFactorDisableRequestDTO struct {
	Password string `json:"password" validate:"required,min=8,max=20"`
	Code     string `json:"code"     validate:"omitempty,min=6,max=20"`
}
